import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { processApi, testApi } from '../services/api';
import { ArrowLeft, ClipboardCheck, Loader2, Trophy } from 'lucide-react';
import TestQuiz from '../components/Test/TestQuiz';
import TestResults from '../components/Test/TestResults';
import LeaderboardTable from '../components/Test/LeaderboardTable';

export default function TestPage() {
  const { id } = useParams();
  const { branch } = useAuth();
  const [doc, setDoc] = useState(null);
  const [phase, setPhase] = useState('idle'); // idle, generating, quiz, submitting, results
  const [questions, setQuestions] = useState([]);
  const [result, setResult] = useState(null);
  const [leaderboard, setLeaderboard] = useState([]);
  const [tab, setTab] = useState('test'); // test, leaderboard
  const [error, setError] = useState('');

  useEffect(() => {
    processApi.getById(id).then(setDoc).catch(() => {});
    testApi.getLeaderboard(id).then(setLeaderboard).catch(() => {});
  }, [id]);

  const handleGenerate = async () => {
    setPhase('generating');
    setError('');
    try {
      const data = await testApi.generate(id);
      setQuestions(data.questions);
      setPhase('quiz');
    } catch (err) {
      setError(err.message || 'Failed to generate test');
      setPhase('idle');
    }
  };

  const handleSubmit = async (answers) => {
    setPhase('submitting');
    try {
      const data = await testApi.submit(id, answers);
      setResult(data);
      setPhase('results');
      testApi.getLeaderboard(id).then(setLeaderboard).catch(() => {});
    } catch (err) {
      setError(err.message || 'Failed to submit test');
      setPhase('quiz');
    }
  };

  const handleRetake = () => {
    setResult(null);
    setQuestions([]);
    setPhase('idle');
  };

  if (!doc) {
    return (
      <div className="flex justify-center py-20">
        <Loader2 size={32} className="animate-spin text-blue-500" />
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto">
      {/* Header */}
      <div className="mb-6">
        <Link to={`/processes/${id}`} className="flex items-center gap-1 text-sm text-blue-600 hover:underline mb-3">
          <ArrowLeft size={14} />
          Back to {doc.title}
        </Link>
        <div className="flex items-center gap-3">
          <div className="bg-green-600 text-white p-2 rounded-lg">
            <ClipboardCheck size={24} />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Process Test</h1>
            <p className="text-sm text-gray-500">{doc.title}</p>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 mb-6 border-b border-gray-200">
        <button
          onClick={() => setTab('test')}
          className={`px-4 py-2 text-sm font-medium border-b-2 transition ${
            tab === 'test' ? 'border-blue-600 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700'
          }`}
        >
          <ClipboardCheck size={14} className="inline mr-1.5" />
          Test
        </button>
        <button
          onClick={() => setTab('leaderboard')}
          className={`px-4 py-2 text-sm font-medium border-b-2 transition ${
            tab === 'leaderboard' ? 'border-blue-600 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700'
          }`}
        >
          <Trophy size={14} className="inline mr-1.5" />
          Leaderboard
        </button>
      </div>

      {tab === 'test' && (
        <>
          {error && (
            <div className="mb-4 px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">
              {error}
            </div>
          )}

          {phase === 'idle' && (
            <div className="text-center py-12 bg-white rounded-xl border border-gray-200">
              <ClipboardCheck size={48} className="mx-auto text-gray-300 mb-4" />
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Ready to Test Your Knowledge?</h3>
              <p className="text-sm text-gray-500 mb-1">10 questions generated by AI from this process document</p>
              <p className="text-sm text-gray-400 mb-6">You need 80% or above to pass</p>
              <button
                onClick={handleGenerate}
                className="px-6 py-2.5 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition"
              >
                Start Test
              </button>
            </div>
          )}

          {phase === 'generating' && (
            <div className="text-center py-16 bg-white rounded-xl border border-gray-200">
              <Loader2 size={40} className="mx-auto text-blue-500 animate-spin mb-4" />
              <p className="text-gray-600 font-medium">Generating test questions with AI...</p>
              <p className="text-sm text-gray-400 mt-1">This may take a few seconds</p>
            </div>
          )}

          {(phase === 'quiz' || phase === 'submitting') && (
            <TestQuiz
              questions={questions}
              onSubmit={handleSubmit}
              submitting={phase === 'submitting'}
            />
          )}

          {phase === 'results' && result && (
            <TestResults
              result={result}
              processId={id}
              onRetake={handleRetake}
            />
          )}
        </>
      )}

      {tab === 'leaderboard' && (
        <div className="bg-white rounded-xl border border-gray-200 p-5">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Leaderboard — {doc.title}</h3>
          <LeaderboardTable entries={leaderboard} currentBranchCode={branch?.code} />
        </div>
      )}
    </div>
  );
}
